# CMake generated Testfile for 
# Source directory: /home/qizi/桌面/miniob/unittest/observer
# Build directory: /home/qizi/桌面/miniob/build_debug/unittest/observer
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(aggregate_hash_table_test "/home/qizi/桌面/miniob/build_debug/unittest/aggregate_hash_table_test")
set_tests_properties(aggregate_hash_table_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(arithmetic_operator_test "/home/qizi/桌面/miniob/build_debug/unittest/arithmetic_operator_test")
set_tests_properties(arithmetic_operator_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(bp_manager_test "/home/qizi/桌面/miniob/build_debug/unittest/bp_manager_test")
set_tests_properties(bp_manager_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(bplus_tree_log_entry_test "/home/qizi/桌面/miniob/build_debug/unittest/bplus_tree_log_entry_test")
set_tests_properties(bplus_tree_log_entry_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(bplus_tree_log_test "/home/qizi/桌面/miniob/build_debug/unittest/bplus_tree_log_test")
set_tests_properties(bplus_tree_log_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(bplus_tree_test "/home/qizi/桌面/miniob/build_debug/unittest/bplus_tree_test")
set_tests_properties(bplus_tree_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(buffer_pool_log_test "/home/qizi/桌面/miniob/build_debug/unittest/buffer_pool_log_test")
set_tests_properties(buffer_pool_log_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(catalog_test "/home/qizi/桌面/miniob/build_debug/unittest/catalog_test")
set_tests_properties(catalog_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(chunk_test "/home/qizi/桌面/miniob/build_debug/unittest/chunk_test")
set_tests_properties(chunk_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(codec_test "/home/qizi/桌面/miniob/build_debug/unittest/codec_test")
set_tests_properties(codec_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(composite_tuple_test "/home/qizi/桌面/miniob/build_debug/unittest/composite_tuple_test")
set_tests_properties(composite_tuple_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(disk_buffer_pool_test "/home/qizi/桌面/miniob/build_debug/unittest/disk_buffer_pool_test")
set_tests_properties(disk_buffer_pool_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(disk_log_handler_test "/home/qizi/桌面/miniob/build_debug/unittest/disk_log_handler_test")
set_tests_properties(disk_log_handler_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(double_write_buffer_test "/home/qizi/桌面/miniob/build_debug/unittest/double_write_buffer_test")
set_tests_properties(double_write_buffer_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(expression_test "/home/qizi/桌面/miniob/build_debug/unittest/expression_test")
set_tests_properties(expression_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(log_buffer_test "/home/qizi/桌面/miniob/build_debug/unittest/log_buffer_test")
set_tests_properties(log_buffer_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(log_entry_test "/home/qizi/桌面/miniob/build_debug/unittest/log_entry_test")
set_tests_properties(log_entry_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(log_file_test "/home/qizi/桌面/miniob/build_debug/unittest/log_file_test")
set_tests_properties(log_file_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(mvcc_trx_log_test "/home/qizi/桌面/miniob/build_debug/unittest/mvcc_trx_log_test")
set_tests_properties(mvcc_trx_log_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(parser_test "/home/qizi/桌面/miniob/build_debug/unittest/parser_test")
set_tests_properties(parser_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(pax_storage_test "/home/qizi/桌面/miniob/build_debug/unittest/pax_storage_test")
set_tests_properties(pax_storage_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(persist_test "/home/qizi/桌面/miniob/build_debug/unittest/persist_test")
set_tests_properties(persist_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(record_manager_test "/home/qizi/桌面/miniob/build_debug/unittest/record_manager_test")
set_tests_properties(record_manager_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(ring_buffer_test "/home/qizi/桌面/miniob/build_debug/unittest/ring_buffer_test")
set_tests_properties(ring_buffer_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(text_and_drop_table_test "/home/qizi/桌面/miniob/build_debug/unittest/text_and_drop_table_test")
set_tests_properties(text_and_drop_table_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;13;add_test;/home/qizi/桌面/miniob/unittest/observer/CMakeLists.txt;0;")
